-- AlterTable
ALTER TABLE "Score" ADD COLUMN     "gameId" INTEGER NOT NULL DEFAULT 1;

-- AddForeignKey
ALTER TABLE "Score" ADD CONSTRAINT "Score_gameId_fkey" FOREIGN KEY ("gameId") REFERENCES "Game"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
